### ISSUE TITLE
Not able to install on Raspberry Pi OS Lite 64bit

### ISSUE THREAD

**Issue by ManicQuinn** [cyb3rdog/vector-python-sdk#9]
error given on the step to check path:
```
pi@escapepod:~ $ python3 -c "import anki_vector as _; print(_.__path__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/anki_vector/__init__.py", line 22, in <module>
    from . import messaging
  File "/usr/local/lib/python3.9/dist-packages/anki_vector/messaging/__init__.py", line 42, in <module>
    from . import protocol
  File "/usr/local/lib/python3.9/dist-packages/anki_vector/messaging/protocol.py", line 24, in <module>
    from .behavior_pb2 import *
  File "/usr/local/lib/python3.9/dist-packages/anki_vector/messaging/behavior_pb2.py", line 16, in <module>
    from anki_vector.messaging import messages_pb2 as anki__vector_dot_messaging_dot_messages__pb2
  File "/usr/local/lib/python3.9/dist-packages/anki_vector/messaging/messages_pb2.py", line 17, in <module>
    from anki_vector.messaging import response_status_pb2 as anki__vector_dot_messaging_dot_response__status__pb2
  File "/usr/local/lib/python3.9/dist-packages/anki_vector/messaging/response_status_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.9/dist-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by ManicQuinn** [comment]
Not sure what I did but reinstalled a few times and it works now, this error still persists outside of this tho when trying to run an example script, I'll make a new issue
